updated site6

diff --git a/.github/workflows/scan.yml b/.github/workflows/scan.yml
--- a/.github/workflows/scan.yml
+++ b/.github/workflows/scan.yml
@@ -56,8 +56,8 @@ jobs:
             --allow-root
 
           if [[ "$site" == "site6-plugin/" ]]; then
-            echo "Installing vulnerable plugin on $site"
-            docker exec wordpress wp plugin install wp-live-chat-support --version=8.0.26 --force --activate --allow-root
+            echo "Activating vulnerable plugin on $site"
+            docker exec wordpress wp plugin activate wp-live-chat-support --allow-root || echo "Activation failed"
           fi
 
           docker exec wordpress wp plugin list --allow-root
