older version

diff --git a/.github/workflows/scan.yml b/.github/workflows/scan.yml
--- a/.github/workflows/scan.yml
+++ b/.github/workflows/scan.yml
@@ -57,7 +57,7 @@ jobs:
 
           if [[ "$site" == "site6-plugin/" ]]; then
             echo "Installing vulnerable plugin on $site"
-            docker exec wordpress wp plugin activate wp-live-chat-support --allow-root || echo "Activation failed"
+            docker exec wordpress wp plugin activate wp-live-chat-support --version=8.0.26 --allow-root || echo "Activation failed"
           fi
 
           docker exec wordpress wp plugin list --allow-root
